# Generated by Django 5.0.6 on 2024-06-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='person',
        ),
    ]
