# Generated by Django 5.0.6 on 2024-06-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_item_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='persons',
            field=models.ManyToManyField(related_name='items', to='services.person'),
        ),
    ]
