# Generated by Django 5.0.6 on 2024-06-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_item_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.item')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.person')),
            ],
            options={
                'unique_together': {('person', 'item')},
            },
        ),
    ]
