# Generated by Django 5.0.6 on 2024-06-11 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_personitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='persons',
        ),
    ]
