# Generated by Django 5.0.6 on 2024-06-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_item_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='person',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
