# Generated by Django 5.0.6 on 2024-06-11 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_order_name_remove_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
