# Generated by Django 5.0.6 on 2024-06-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeperson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
