# Generated by Django 5.0.6 on 2024-06-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
