# Generated by Django 5.0.6 on 2024-06-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_person_location_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
