# Generated by Django 5.0.6 on 2024-09-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_ordercourier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercourier',
            old_name='what',
            new_name='objectSended',
        ),
    ]
