# Generated by Django 5.0.6 on 2024-09-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_rename_what_ordercourier_objectsended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordercourier',
            old_name='objectSended',
            new_name='objectSent',
        ),
    ]
