# Generated by Django 5.0.6 on 2024-10-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_ordercourier'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercourier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3.25, max_digits=10),
        ),
    ]
